# 消费者 consumer 服务的配置文件
#spring:
#  profiles:
#    active:
#    - test
# 开发环境配置
---
server:
  port: 8080
info:
  app.name: mcloud-service-consumer
  app.author: vostroi
  build.artifactId: consumer
  build.groupId: com.vostroi
spring:
  profiles: dev     #开发环境
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://mcloud-eureka-server-03:9529/eureka/,http://mcloud-eureka-server-02:9528/eureka/,http://mcloud-eureka-server-01:9527/eureka/
    #      defaultZone: http://mcloud-eureka-server-01:9527/eureka/
    fetch-registry: true
  instance:
    instance-id: consumer-8080
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true #对超时请求启用重试机制
  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
  MaxAutoRetries: 1 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #修改负载均衡算法(最小返回时间)
  # 可配置属性 见 com.netflix.client.config.CommonClientConfigKey
feign:
  hystrix:
    enabled: true # 客户端开启服务降级
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
# 测试环境配置
---
server:
  port: 8081
info:
  app.name: mcloud-service-consumer
  app.author: vostroi
  build.artifactId: consumer
  build.groupId: com.vostroi
spring:
  profiles: test     #测试环境
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://mcloud-eureka-server-0303:9539/eureka/,http://mcloud-eureka-server-0202:9538/eureka/,http://mcloud-eureka-server-0101:9537/eureka/
    #      defaultZone: http://mcloud-eureka-server-01:9527/eureka/
    fetch-registry: true
  instance:
    instance-id: consumer-8081
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true #对超时请求启用重试机制
  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
  MaxAutoRetries: 1 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #修改负载均衡算法(最小返回时间)
  # 可配置属性 见 com.netflix.client.config.CommonClientConfigKey
feign:
  hystrix:
    enabled: true # 客户端开启服务降级
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

 
 
